export const EDITOR_MODES = {
  EDIT: 'EDIT',
  ANALYZE: 'ANALYZE',
};

export const NODE_TYPES = {
  VARIABLE: 'VARIABLE',
  FACTOR: 'FACTOR',
  FACTOR_INPUT: 'FACTOR_INPUT',
  FACTOR_OUTPUT: 'FACTOR_OUTPUT',
};

export const VARIABLE_TYPES = {
  LATENT: 'LATENT',
  EVIDENCE: 'EVIDENCE',
  QUERY: 'QUERY',
};
